### ISSUE TITLE
Marfa Dark Theme results in illegible stats

### ISSUE THREAD

**Issue by andrewcanion** [am1t/plugin-post-stats#4]
I've noticed that when using the Marfa Dark Theme (via micro.blog plugin), the Stats page doesn't render well. See https://canion.blog/stats/

**Comment by am1t** [comment]
Thank you for that feedback, Andrew. I wish I could fix it with plugin's styling. At least, I am not aware of a fix that will cover table styling for all the themes. For Marfa specifically, you could add below snippet in custom CSS ("Design" -> "Edit CSS"). 

```
tr:nth-child(odd)>td {
  background: initial;
}
```

Let me know if you think there's a better way.

**Comment by andrewcanion** [comment]
Thanks Amit. After I posted this support issue I realised that it was a common problem with tables across Marfa. I've inserted your CSS, which you are right does seem to make the most sense. Thank you!
