### ISSUE TITLE
Category cloud hyperlinks all go to the home page

### ISSUE THREAD

**Issue by mjdescy** [am1t/plugin-post-stats#5]
All the links in the "Category Cloud for Posts" section of my Stats page on my [Micro.blog-hosted blog](https://micro.mjdescy.me/stats/) open the site root rather than a list of category-specific posts. The URLs in the hyperlinks appear to be correct. Is the Stats plugin failing to generate the category pages?

**Comment by mjdescy** [comment]
This was a bug in the Hello theme on Micro.blog.

**Comment by am1t** [comment]
I see it working, hope it's no longer an issue.
